version: '3.9'

services:

  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html

  mongodb:
    image: mongo:6.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    volumes:
      - ./docker/mongodb:/data/db